import type { BragoTemplateMeta } from "@/lib/server/poster-templates/shared/types";

// 这个文件可以被 client 端 import。
// 不要在这里 import 任何 lib/server/poster-templates/ 下的渲染逻辑。

export const POSTER_TEMPLATES: BragoTemplateMeta[] = [
  {
    id: "pressure_driveway_hero_split",
    name: "Driveway Hero Split",
    industry: "pressure_washing",
    channel: "google_business_profile",
    layoutFamily: "hero_photo",
    photoPairCount: 1,
    intent: "trust",
    phoneDefault: "visible",
    previewImage: "/template-previews/pressure_driveway_hero_split.webp",
  },
  {
    id: "pressure_driveway_stacked",
    name: "Driveway Bold Stacked",
    industry: "pressure_washing",
    channel: "instagram",
    layoutFamily: "stacked",
    photoPairCount: 1,
    intent: "portfolio",
    phoneDefault: "hidden",
    previewImage: "/template-previews/pressure_driveway_stacked.webp",
  },
  {
    id: "pressure_driveway_local_share",
    name: "Local Job Share",
    industry: "pressure_washing",
    channel: "facebook_nextdoor",
    layoutFamily: "split",
    photoPairCount: 1,
    intent: "recent_job",
    phoneDefault: "subtle",
    previewImage: "/template-previews/pressure_driveway_local_share.webp",
  },
  {
    id: "pressure_driveway_review_trust",
    name: "Review Trust Square",
    industry: "pressure_washing",
    channel: "google_business_profile",
    layoutFamily: "split",
    photoPairCount: 1,
    intent: "trust",
    phoneDefault: "subtle",
    previewImage: "/template-previews/pressure_driveway_review_trust.webp",
  },
  {
    id: "pressure_driveway_soft_quote",
    name: "Soft Quote Proof",
    industry: "pressure_washing",
    channel: "facebook_nextdoor",
    layoutFamily: "split",
    photoPairCount: 1,
    intent: "quote",
    phoneDefault: "hidden",
    previewImage: "/template-previews/pressure_driveway_soft_quote.webp",
  },
  {
    id: "pressure_driveway_neighborhood",
    name: "Neighborhood Before/After",
    industry: "pressure_washing",
    channel: "facebook_nextdoor",
    layoutFamily: "card_pair",
    photoPairCount: 1,
    intent: "recent_job",
    phoneDefault: "hidden",
    previewImage: "/template-previews/pressure_driveway_neighborhood.webp",
  },
  {
    id: "pressure_driveway_project_no",
    name: "Project No. Square",
    industry: "pressure_washing",
    channel: "instagram",
    layoutFamily: "stacked",
    photoPairCount: 1,
    intent: "portfolio",
    phoneDefault: "hidden",
    previewImage: "/template-previews/pressure_driveway_project_no.webp",
  },
  {
    id: "pressure_driveway_portfolio_split",
    name: "Portfolio Clean Split",
    industry: "pressure_washing",
    channel: "instagram",
    layoutFamily: "split",
    photoPairCount: 1,
    intent: "portfolio",
    phoneDefault: "hidden",
    previewImage: "/template-previews/pressure_driveway_portfolio_split.webp",
  },
  {
    id: "detail_interior_proof",
    name: "Interior Detail Proof",
    industry: "auto_detailing",
    channel: "google_business_profile",
    layoutFamily: "hero_photo",
    photoPairCount: 1,
    intent: "trust",
    phoneDefault: "visible",
    previewImage: "/template-previews/detail_interior_proof.webp",
  },
  {
    id: "detail_review_badge",
    name: "Review Badge Detail",
    industry: "auto_detailing",
    channel: "google_business_profile",
    layoutFamily: "split",
    photoPairCount: 1,
    intent: "trust",
    phoneDefault: "subtle",
    previewImage: "/template-previews/detail_review_badge.webp",
  },
  {
    id: "detail_mobile_local_share",
    name: "Mobile Detail Local Share",
    industry: "auto_detailing",
    channel: "facebook_nextdoor",
    layoutFamily: "split",
    photoPairCount: 1,
    intent: "recent_job",
    phoneDefault: "subtle",
    previewImage: "/template-previews/detail_mobile_local_share.webp",
  },
  {
    id: "detail_pet_hair_quote",
    name: "Pet Hair Gone Quote",
    industry: "auto_detailing",
    channel: "facebook_nextdoor",
    layoutFamily: "stacked",
    photoPairCount: 1,
    intent: "quote",
    phoneDefault: "subtle",
    previewImage: "/template-previews/detail_pet_hair_quote.webp",
  },
  {
    id: "detail_driveway_proof",
    name: "Driveway Detail Proof",
    industry: "auto_detailing",
    channel: "facebook_nextdoor",
    layoutFamily: "stacked",
    photoPairCount: 1,
    intent: "recent_job",
    phoneDefault: "subtle",
    previewImage: "/template-previews/detail_driveway_proof.webp",
  },
  {
    id: "detail_portfolio_shine_split",
    name: "Portfolio Shine Split",
    industry: "auto_detailing",
    channel: "instagram",
    layoutFamily: "split",
    photoPairCount: 1,
    intent: "portfolio",
    phoneDefault: "hidden",
    previewImage: "/template-previews/detail_portfolio_shine_split.webp",
  },
  {
    id: "detail_project_no",
    name: "Project No. Detail",
    industry: "auto_detailing",
    channel: "instagram",
    layoutFamily: "stacked",
    photoPairCount: 1,
    intent: "portfolio",
    phoneDefault: "hidden",
    previewImage: "/template-previews/detail_project_no.webp",
  },
  {
    id: "pressure_exterior_multi_area_proof",
    name: "Exterior Multi-area Proof",
    industry: "pressure_washing",
    channel: "facebook_nextdoor",
    layoutFamily: "collage",
    photoPairCount: 4,
    intent: "recent_job",
    phoneDefault: "subtle",
    previewImage: "/template-previews/pressure_exterior_multi_area_proof.webp",
  },
  {
    id: "detail_full_multi_area_proof",
    name: "Full Detail Multi-area Proof",
    industry: "auto_detailing",
    channel: "facebook_nextdoor",
    layoutFamily: "collage",
    photoPairCount: 4,
    intent: "recent_job",
    phoneDefault: "subtle",
    previewImage: "/template-previews/detail_full_multi_area_proof.webp",
  },
];

export function getTemplateById(id: string): BragoTemplateMeta | undefined {
  return POSTER_TEMPLATES.find((t) => t.id === id);
}
