// This file is auto-generated by scripts/generate-blog-manifest.mjs
// Do not edit manually.

type BlogModuleLoader = () => Promise<unknown>;
type BlogManifest = Record<string, Record<string, BlogModuleLoader>>;

export const blogModuleLoaders: BlogManifest = {
};
