// This file is auto-generated by scripts/generate-blog-manifest.mjs
// Do not edit manually.

export const blogModuleLoaders = {
  "changelog-for-2025": {
    "en": () => import("../app/[locale]/(marketing)/blog/changelog-for-2025/en.mdx"),
  },
  "cool-things-to-do-with-ai": {
    "en": () => import("../app/[locale]/(marketing)/blog/cool-things-to-do-with-ai/en.mdx"),
  },
  "how-companies-are-working-without-ai": {
    "en": () => import("../app/[locale]/(marketing)/blog/how-companies-are-working-without-ai/en.mdx"),
  },
  "top-5-llm-of-all-time": {
    "en": () => import("../app/[locale]/(marketing)/blog/top-5-llm-of-all-time/en.mdx"),
  },
  "what-is-ai-anyway": {
    "en": () => import("../app/[locale]/(marketing)/blog/what-is-ai-anyway/en.mdx"),
  },
} as const;
