import type { GoogleCaptionTemplate } from "@/lib/brago/types";

export const PRESSURE_TEMPLATES: GoogleCaptionTemplate[] = [
  {
    id: "pw_driveway_seasonal_1",
    industry: "pressure_washing",
    serviceTypes: ["driveway"],
    seasons: ["spring", "summer", "fall", "any"],
    themes: ["grime", "concrete"],
    tone: "neighborly",
    templateText:
      "Knocked out a driveway in {city} today. Years of grime and dark stains came off the concrete and it looks bright again. If yours is starting to look the same, the Call button on our Google profile is the easiest way to reach us.",
    avoid: ["transformation", "amazing"],
    example: "Knocked out a driveway in South Austin today.",
  },
  {
    id: "pw_driveway_2",
    industry: "pressure_washing",
    serviceTypes: ["driveway"],
    seasons: ["any"],
    themes: ["oil_stains", "concrete"],
    tone: "casual",
    templateText:
      "Cleaned up a driveway over in {city}. Took our time on the oil spots and the result is a much cleaner surface. Happy to help with yours if it could use the same treatment.",
    avoid: ["transformation"],
    example: "Cleaned up a driveway over in Round Rock.",
  },
  {
    id: "pw_patio_1",
    industry: "pressure_washing",
    serviceTypes: ["patio"],
    seasons: ["spring", "summer"],
    themes: ["mold", "outdoor_living"],
    tone: "neighborly",
    templateText:
      "Patio in {city} got a deep clean today. Cleared off the green mildew that builds up after a wet stretch, so it is ready for the next cookout.",
    avoid: ["grill out"],
    example: "Patio in San Marcos got a deep clean today.",
  },
  {
    id: "pw_patio_2",
    industry: "pressure_washing",
    serviceTypes: ["patio"],
    seasons: ["any"],
    themes: ["outdoor_living"],
    tone: "casual",
    templateText:
      "Spent the morning bringing a tired patio in {city} back to a usable space. Pavers came out a noticeably cleaner color.",
    avoid: ["amazing"],
    example: "Spent the morning bringing a tired patio in Plano back to a usable space.",
  },
  {
    id: "pw_house_wash_1",
    industry: "pressure_washing",
    serviceTypes: ["siding", "house wash"],
    seasons: ["any"],
    themes: ["curb_appeal"],
    tone: "professional",
    templateText:
      "House wash done in {city}. Soft-washed the siding so we did not push water behind the panels, and pulled off the buildup that makes a place look dingy from the street.",
    avoid: ["curb appeal"],
    example: "House wash done in Cedar Park.",
  },
  {
    id: "pw_house_wash_2",
    industry: "pressure_washing",
    serviceTypes: ["siding", "house wash"],
    seasons: ["spring", "summer"],
    themes: ["mildew"],
    tone: "neighborly",
    templateText:
      "Washed a house in {city} this afternoon. The north side had the usual mildew streaks from the shaded run-off, and they came clean.",
    avoid: ["transformation"],
    example: "Washed a house in Pflugerville this afternoon.",
  },
  {
    id: "pw_walkway_1",
    industry: "pressure_washing",
    serviceTypes: ["walkway"],
    seasons: ["spring", "summer", "fall"],
    themes: ["algae", "safety"],
    tone: "professional",
    templateText:
      "Walkway cleaning in {city}. Took the slick algae layer off so it is safer to walk on, and the brick color came back through.",
    avoid: ["like new"],
    example: "Walkway cleaning in Buda.",
  },
  {
    id: "pw_walkway_2",
    industry: "pressure_washing",
    serviceTypes: ["walkway"],
    seasons: ["any"],
    themes: ["brick"],
    tone: "casual",
    templateText:
      "Front walkway in {city} got the treatment today. Worked the joints carefully so we did not blow out the mortar.",
    avoid: ["transformation"],
    example: "Front walkway in Lakeway got the treatment today.",
  },
  {
    id: "pw_deck_1",
    industry: "pressure_washing",
    serviceTypes: ["deck"],
    seasons: ["spring", "summer"],
    themes: ["wood"],
    tone: "professional",
    templateText:
      "Deck wash in {city}. Used a lower pressure pass for the wood grain and the boards came out cleaner without raising fibers.",
    avoid: ["amazing"],
    example: "Deck wash in Manor.",
  },
  {
    id: "pw_deck_2",
    industry: "pressure_washing",
    serviceTypes: ["deck"],
    seasons: ["summer"],
    themes: ["wood", "summer"],
    tone: "neighborly",
    templateText:
      "Took care of a deck in {city} before the weekend. Now it is ready for cookouts and bare feet.",
    avoid: ["transformation"],
    example: "Took care of a deck in Round Rock before the weekend.",
  },
  {
    id: "pw_fence_1",
    industry: "pressure_washing",
    serviceTypes: ["fence"],
    seasons: ["any"],
    themes: ["wood"],
    tone: "casual",
    templateText:
      "Cleaned a wood fence run in {city}. Years of weather grime came off and the wood is ready to take a fresh seal.",
    avoid: ["transformation"],
    example: "Cleaned a wood fence run in Hutto.",
  },
  {
    id: "pw_oil_1",
    industry: "pressure_washing",
    serviceTypes: ["driveway", "oil stain"],
    seasons: ["any"],
    themes: ["oil_stains"],
    tone: "professional",
    templateText:
      "Worked on stubborn oil stains in a driveway in {city}. Treated the spots first, then surface cleaned across the slab so the color matches edge to edge.",
    avoid: ["transformation"],
    example: "Worked on stubborn oil stains in a driveway in Leander.",
  },
  {
    id: "pw_commercial_1",
    industry: "pressure_washing",
    serviceTypes: ["commercial", "storefront"],
    seasons: ["any"],
    themes: ["commercial"],
    tone: "professional",
    templateText:
      "Storefront sidewalk cleaning in {city}. We scheduled it before opening so the foot traffic stayed off the wet pavers.",
    avoid: ["amazing"],
    example: "Storefront sidewalk cleaning in Bee Cave.",
  },
  {
    id: "pw_roof_1",
    industry: "pressure_washing",
    serviceTypes: ["roof"],
    seasons: ["any"],
    themes: ["roof"],
    tone: "professional",
    templateText:
      "Soft wash on a roof in {city}. Used the right mix on the shingles so the dark streaks lifted without pressure damage.",
    avoid: ["transformation"],
    example: "Soft wash on a roof in Georgetown.",
  },
  {
    id: "pw_winter_1",
    industry: "pressure_washing",
    serviceTypes: ["driveway", "walkway"],
    seasons: ["winter"],
    themes: ["winter"],
    tone: "professional",
    templateText:
      "Got a job done in {city} before the next cold snap. Cleared off the build-up while the weather still cooperated.",
    avoid: ["amazing"],
    example: "Got a job done in McKinney before the next cold snap.",
  },
  {
    id: "pw_fall_1",
    industry: "pressure_washing",
    serviceTypes: ["driveway", "walkway"],
    seasons: ["fall"],
    themes: ["fall", "leaves"],
    tone: "neighborly",
    templateText:
      "Cleaned up after a long leaf-fall season in {city}. The tannin staining lifted off the concrete and brightened the whole entry.",
    avoid: ["transformation"],
    example: "Cleaned up after a long leaf-fall season in Frisco.",
  },
  {
    id: "pw_pre_paint_1",
    industry: "pressure_washing",
    serviceTypes: ["siding", "house wash"],
    seasons: ["any"],
    themes: ["pre_paint"],
    tone: "professional",
    templateText:
      "Pre-paint house wash in {city}. Pulled off the chalking and grime so the new coat has a clean surface to bond to.",
    avoid: ["transformation"],
    example: "Pre-paint house wash in Allen.",
  },
  {
    id: "pw_storm_1",
    industry: "pressure_washing",
    serviceTypes: ["driveway", "patio"],
    seasons: ["spring", "fall"],
    themes: ["storm_cleanup"],
    tone: "neighborly",
    templateText:
      "Cleaned up after the last round of storms in {city}. The mud splash on the lower siding and pavers all came off in one pass.",
    avoid: ["amazing"],
    example: "Cleaned up after the last round of storms in Garland.",
  },
];
