import type { GoogleCaptionTemplate } from "@/lib/brago/types";

export const CLEANING_TEMPLATES: GoogleCaptionTemplate[] = [
  {
    id: "cl_carpet_1",
    industry: "cleaning",
    serviceTypes: ["carpet cleaning"],
    seasons: ["any"],
    themes: ["carpet"],
    tone: "professional",
    templateText:
      "Carpet cleaning in {city}. Pulled out the deep traffic-lane soil with a hot water extraction pass.",
    avoid: ["transformation"],
    example: "Carpet cleaning in Tomball.",
  },
  {
    id: "cl_carpet_pet_1",
    industry: "cleaning",
    serviceTypes: ["carpet cleaning", "pet stain"],
    seasons: ["any"],
    themes: ["carpet", "pet"],
    tone: "neighborly",
    templateText:
      "Pet-stain treatment in {city}. Treated the spots at the pad and the smell along with them.",
    avoid: ["amazing"],
    example: "Pet-stain treatment in Spring.",
  },
  {
    id: "cl_moveout_1",
    industry: "cleaning",
    serviceTypes: ["move-out cleaning"],
    seasons: ["any"],
    themes: ["move_out"],
    tone: "professional",
    templateText:
      "Move-out cleaning in {city}. Detailed the kitchen and bathrooms so the inspection goes smoothly.",
    avoid: ["transformation"],
    example: "Move-out cleaning in Sugar Land.",
  },
  {
    id: "cl_movein_1",
    industry: "cleaning",
    serviceTypes: ["move-in cleaning"],
    seasons: ["any"],
    themes: ["move_in"],
    tone: "neighborly",
    templateText:
      "Move-in clean in {city}. Wiped down cabinets and reset the spaces before the family unpacks.",
    avoid: ["amazing"],
    example: "Move-in clean in Katy.",
  },
  {
    id: "cl_window_1",
    industry: "cleaning",
    serviceTypes: ["window cleaning"],
    seasons: ["any"],
    themes: ["windows"],
    tone: "professional",
    templateText:
      "Window cleaning in {city}. Squeegeed both sides so the light comes through clear without streaks.",
    avoid: ["amazing"],
    example: "Window cleaning in Pearland.",
  },
  {
    id: "cl_window_high_1",
    industry: "cleaning",
    serviceTypes: ["window cleaning", "exterior windows"],
    seasons: ["any"],
    themes: ["windows", "exterior"],
    tone: "professional",
    templateText:
      "Exterior window cleaning in {city}. Used the pure-water pole for the upper panes so there were no ladder marks on the siding.",
    avoid: ["transformation"],
    example: "Exterior window cleaning in Cypress.",
  },
  {
    id: "cl_commercial_1",
    industry: "cleaning",
    serviceTypes: ["commercial cleaning"],
    seasons: ["any"],
    themes: ["commercial"],
    tone: "professional",
    templateText:
      "Commercial cleaning in {city}. Reset the break room and bathrooms before the morning shift.",
    avoid: ["amazing"],
    example: "Commercial cleaning in Humble.",
  },
  {
    id: "cl_office_1",
    industry: "cleaning",
    serviceTypes: ["office cleaning"],
    seasons: ["any"],
    themes: ["office"],
    tone: "professional",
    templateText:
      "Office cleaning in {city}. Detailed the high-touch surfaces and reset the kitchen.",
    avoid: ["transformation"],
    example: "Office cleaning in Round Rock.",
  },
  {
    id: "cl_airbnb_1",
    industry: "cleaning",
    serviceTypes: ["short term rental"],
    seasons: ["any"],
    themes: ["str", "turnover"],
    tone: "professional",
    templateText:
      "Turnover clean in {city}. Linens fresh, kitchen reset, bathrooms polished for the next guest check-in.",
    avoid: ["amazing"],
    example: "Turnover clean in San Antonio.",
  },
  {
    id: "cl_deep_1",
    industry: "cleaning",
    serviceTypes: ["deep clean"],
    seasons: ["any"],
    themes: ["deep"],
    tone: "neighborly",
    templateText:
      "Deep clean in {city}. Got the baseboards and behind the appliances that do not usually make it into a regular service.",
    avoid: ["transformation"],
    example: "Deep clean in Conroe.",
  },
  {
    id: "cl_post_construction_1",
    industry: "cleaning",
    serviceTypes: ["post construction"],
    seasons: ["any"],
    themes: ["post_construction"],
    tone: "professional",
    templateText:
      "Post-construction clean in {city}. Pulled drywall dust off every surface so the owners could walk in fresh.",
    avoid: ["amazing"],
    example: "Post-construction clean in Friendswood.",
  },
  {
    id: "cl_recurring_1",
    industry: "cleaning",
    serviceTypes: ["recurring cleaning"],
    seasons: ["any"],
    themes: ["recurring"],
    tone: "casual",
    templateText:
      "Recurring clean for a family in {city}. Same team each visit so they get consistent results.",
    avoid: ["amazing"],
    example: "Recurring clean for a family in Magnolia.",
  },
  {
    id: "cl_upholstery_1",
    industry: "cleaning",
    serviceTypes: ["upholstery cleaning"],
    seasons: ["any"],
    themes: ["upholstery"],
    tone: "professional",
    templateText:
      "Upholstery cleaning in {city}. Worked a sectional that had years of daily use and lifted the embedded soil.",
    avoid: ["transformation"],
    example: "Upholstery cleaning in League City.",
  },
  {
    id: "cl_tile_grout_1",
    industry: "cleaning",
    serviceTypes: ["tile and grout"],
    seasons: ["any"],
    themes: ["tile"],
    tone: "professional",
    templateText:
      "Tile and grout cleaning in {city}. Brought the grout lines back to their original color in the kitchen.",
    avoid: ["amazing"],
    example: "Tile and grout cleaning in Kingwood.",
  },
  {
    id: "cl_winter_1",
    industry: "cleaning",
    serviceTypes: ["deep clean", "window cleaning"],
    seasons: ["winter"],
    themes: ["winter"],
    tone: "neighborly",
    templateText:
      "Pre-holiday reset in {city}. Cleared the windows and high dust so the house photographs well for family visits.",
    avoid: ["amazing"],
    example: "Pre-holiday reset in Friendswood.",
  },
  {
    id: "cl_spring_1",
    industry: "cleaning",
    serviceTypes: ["deep clean"],
    seasons: ["spring"],
    themes: ["spring"],
    tone: "neighborly",
    templateText:
      "Spring deep clean in {city}. Reset the rooms that did not get touched over the winter.",
    avoid: ["amazing"],
    example: "Spring deep clean in Frisco.",
  },
];
