import type { GoogleCaptionTemplate } from "@/lib/brago/types";

export const DETAILING_TEMPLATES: GoogleCaptionTemplate[] = [
  {
    id: "ad_interior_1",
    industry: "auto_detailing",
    serviceTypes: ["interior detail"],
    seasons: ["any"],
    themes: ["interior"],
    tone: "professional",
    templateText:
      "Full interior detail done in {city}. Pulled embedded dirt from the carpet and treated the panels so the cabin feels cared for again.",
    avoid: ["showroom"],
    example: "Full interior detail done in Frisco.",
  },
  {
    id: "ad_interior_pet_1",
    industry: "auto_detailing",
    serviceTypes: ["pet hair", "interior detail"],
    seasons: ["any"],
    themes: ["pet_hair"],
    tone: "neighborly",
    templateText:
      "Pet-hair removal in {city}. Worked the seats and carpets until the hair was actually out of the fibers, not just sitting on top.",
    avoid: ["amazing"],
    example: "Pet-hair removal in The Colony.",
  },
  {
    id: "ad_exterior_1",
    industry: "auto_detailing",
    serviceTypes: ["exterior wash"],
    seasons: ["any"],
    themes: ["paint"],
    tone: "professional",
    templateText:
      "Exterior wash and decontamination in {city}. Took the bonded contamination off the paint so it feels smooth again.",
    avoid: ["transformation"],
    example: "Exterior wash and decontamination in Plano.",
  },
  {
    id: "ad_paint_correction_1",
    industry: "auto_detailing",
    serviceTypes: ["paint correction"],
    seasons: ["any"],
    themes: ["paint"],
    tone: "premium",
    templateText:
      "Paint correction stage in {city}. Pulled out the swirl marks under direct light so the gloss reads cleaner than before.",
    avoid: ["transformation"],
    example: "Paint correction stage in Southlake.",
  },
  {
    id: "ad_ceramic_1",
    industry: "auto_detailing",
    serviceTypes: ["ceramic coating"],
    seasons: ["any"],
    themes: ["ceramic"],
    tone: "premium",
    templateText:
      "Ceramic coating applied in {city}. Surface prep took most of the day so the coating could bond to clean paint.",
    avoid: ["lifetime"],
    example: "Ceramic coating applied in Westlake.",
  },
  {
    id: "ad_wheel_1",
    industry: "auto_detailing",
    serviceTypes: ["wheel cleaning"],
    seasons: ["any"],
    themes: ["wheels"],
    tone: "casual",
    templateText:
      "Wheel and brake-dust cleaning in {city}. The barrels and faces came back to bare metal without acid.",
    avoid: ["amazing"],
    example: "Wheel and brake-dust cleaning in McKinney.",
  },
  {
    id: "ad_engine_1",
    industry: "auto_detailing",
    serviceTypes: ["engine bay"],
    seasons: ["any"],
    themes: ["engine_bay"],
    tone: "professional",
    templateText:
      "Engine bay refresh in {city}. Degreased and dressed without soaking the sensitive components.",
    avoid: ["transformation"],
    example: "Engine bay refresh in Allen.",
  },
  {
    id: "ad_mobile_1",
    industry: "auto_detailing",
    serviceTypes: ["mobile detail"],
    seasons: ["any"],
    themes: ["mobile"],
    tone: "neighborly",
    templateText:
      "Mobile detail at a driveway in {city} today. Brought water and power with us so the customer did not have to lift a finger.",
    avoid: ["doorstep"],
    example: "Mobile detail at a driveway in Carrollton.",
  },
  {
    id: "ad_pre_sale_1",
    industry: "auto_detailing",
    serviceTypes: ["exterior wash", "interior detail"],
    seasons: ["any"],
    themes: ["resale"],
    tone: "professional",
    templateText:
      "Pre-sale detail in {city}. The owner wanted the car to photograph well for the listing, so we focused on paint and interior plastics.",
    avoid: ["transformation"],
    example: "Pre-sale detail in Lewisville.",
  },
  {
    id: "ad_truck_1",
    industry: "auto_detailing",
    serviceTypes: ["interior detail", "exterior wash"],
    seasons: ["any"],
    themes: ["truck"],
    tone: "casual",
    templateText:
      "Work truck refresh in {city}. Lots of caked-in mud and tool dust came out of the cab and bed.",
    avoid: ["amazing"],
    example: "Work truck refresh in Wylie.",
  },
  {
    id: "ad_winter_1",
    industry: "auto_detailing",
    serviceTypes: ["exterior wash"],
    seasons: ["winter"],
    themes: ["winter", "salt"],
    tone: "professional",
    templateText:
      "Salt and road-grime wash in {city}. Got the underbody and wheel wells before the next cold week.",
    avoid: ["amazing"],
    example: "Salt and road-grime wash in Rockwall.",
  },
  {
    id: "ad_summer_1",
    industry: "auto_detailing",
    serviceTypes: ["interior detail"],
    seasons: ["summer"],
    themes: ["summer", "uv"],
    tone: "neighborly",
    templateText:
      "Cabin reset in {city} before the next heat wave. The dash and panels got UV protection and feel cooler to the touch.",
    avoid: ["amazing"],
    example: "Cabin reset in Mansfield before the next heat wave.",
  },
  {
    id: "ad_polish_1",
    industry: "auto_detailing",
    serviceTypes: ["polish"],
    seasons: ["any"],
    themes: ["paint"],
    tone: "premium",
    templateText:
      "Single-stage polish on a daily driver in {city}. The clarity in the reflections changed noticeably.",
    avoid: ["transformation"],
    example: "Single-stage polish on a daily driver in Coppell.",
  },
  {
    id: "ad_headlight_1",
    industry: "auto_detailing",
    serviceTypes: ["headlight restoration"],
    seasons: ["any"],
    themes: ["headlights"],
    tone: "professional",
    templateText:
      "Headlight restoration in {city}. Took the yellow haze off and sealed them so they stay clear longer.",
    avoid: ["amazing"],
    example: "Headlight restoration in Richardson.",
  },
  {
    id: "ad_leather_1",
    industry: "auto_detailing",
    serviceTypes: ["interior detail", "leather"],
    seasons: ["any"],
    themes: ["leather"],
    tone: "premium",
    templateText:
      "Leather clean and condition in {city}. Lifted the dye transfer from the bolsters and put moisture back into the seat.",
    avoid: ["amazing"],
    example: "Leather clean and condition in Highland Park.",
  },
  {
    id: "ad_maintenance_1",
    industry: "auto_detailing",
    serviceTypes: ["exterior wash"],
    seasons: ["any"],
    themes: ["maintenance"],
    tone: "casual",
    templateText:
      "Maintenance wash in {city}. Hand-washed two-bucket method so the paint stays scratch-free between bigger services.",
    avoid: ["transformation"],
    example: "Maintenance wash in Irving.",
  },
];
